paths-ignore:
		-		"node_modules/**"
		-		"dist/**"
		-		"coverage/**"
		-		"e2e/**"
		-		"public/**"
		-		"scripts/**"
		-		".amplify/**"
		-		"amplify/**"
		-		"amplify-backup/**"
		-		"doco/**"
		-		"**/*.d.ts"
		-		"**/*.config.js"
		-		"**/*.config.ts"
		-		"vite.config.js"
		-		"vitest.config.js"
		-		"tailwind.config.js"
		-		"postcss.config.js"
		-		"eslint.config.js"
		-		"biome.json"
		-		"setup-env.js"
		-		"playwright.config.ts"
		-		"report.json"
		-		"coverage-dev.HTML"
		-		"index.html"
		-		"README.md"
		-		"package.json"
		-		"package-lock.json"
		-		"tsconfig.json"
		-		"tsconfig.*.json"
		-		"vite-env.d.ts"
		-		"_mocks/**"
		-		"src/**/*.test.tsx"
		-		"src/**/*.test.ts"
		-		"src/**/*.spec.tsx"
		-		"src/**/*.spec.ts"
